namespace ClickHouseSchemaGen.Generation;

public static class KafkaTableGenerator
{
    public static string Generate(KafkaTableConfig config, IReadOnlyList<ClickHouseColumn> columns)
    {
        var builder = new StringBuilder()
            .AppendLine("-- Generated by ClickHouseSchemaGen. Do not edit manually.")
            .AppendLine()
            .AppendLine($"CREATE TABLE {config.TableName}")
            .AppendLine("(");

        for (var i = 0; i < columns.Count; i++)
        {
            var column = columns[i];
            var comma = i < columns.Count - 1 ? "," : string.Empty;
            builder.AppendLine(SqlColumnFormatter.FormatColumnLine(column.Name, column.Type, column.Comment, comma));
        }

        builder.AppendLine(")")
            .AppendLine("ENGINE = Kafka")
            .AppendLine("SETTINGS");

        List<string> settings =
        [
            $"kafka_broker_list = '{config.Kafka.BrokerList}'",
            $"kafka_topic_list = '{config.Kafka.Topic}'",
            $"kafka_group_name = '{config.Kafka.GroupName}'",
            "kafka_format = 'ProtobufSingle'",
            $"kafka_schema = '{config.ProtoFile}:{config.MessageName}'",
            $"kafka_schema_registry_skip_bytes = {config.Kafka.SkipBytes}",
            $"kafka_num_consumers = {config.Kafka.NumConsumers}"
        ];

        if (RequiresFlattenNested(columns, config))
            settings.Add("flatten_nested = 0");

        if (config.Kafka.ProtobufOneofPresence && columns.Any(IsOneofPresenceColumn))
            settings.Add("input_format_protobuf_oneof_presence = 1");

        if (config.Kafka.ProtobufFlattenGoogleWrappers && columns.Any(column => column.Strategy == MappingStrategy.WellKnownType))
            settings.Add("input_format_protobuf_flatten_google_wrappers = 1");

        SqlScriptWriter.AppendCommaSeparatedLines(builder, settings);
        builder.AppendLine();

        return builder.ToString();
    }

    private static bool IsOneofPresenceColumn(ClickHouseColumn column) =>
        column.Comment == "oneof presence";

    private static bool RequiresFlattenNested(IReadOnlyList<ClickHouseColumn> columns, KafkaTableConfig config)
    {
        if (config.Kafka.FlattenNested)
            return false;

        return columns.Any(column => column.Type.StartsWith("Nested(", StringComparison.Ordinal));
    }
}
