namespace ClickHouseSchemaGen.Generation;

internal static class SqlScriptWriter
{
    public const string GeneratedHeader = "-- Generated by ClickHouseSchemaGen. Do not edit manually.";

    public static void AppendCommaSeparatedLines(
        StringBuilder builder,
        IReadOnlyList<string> lines,
        string lastLineSuffix = ";",
        string linePrefix = "    ")
    {
        for (var i = 0; i < lines.Count; i++)
        {
            var suffix = i < lines.Count - 1 ? "," : lastLineSuffix;
            builder.AppendLine($"{linePrefix}{lines[i]}{suffix}");
        }
    }

    public static void AppendColumnDefinitions(StringBuilder builder, IReadOnlyList<ClickHouseColumn> columns) =>
        AppendColumnDefinitions(
            builder,
            columns,
            column => (column.Name, column.Type, column.Comment));

    public static void AppendColumnDefinitions(StringBuilder builder, IReadOnlyList<PipelineColumnConfig> columns) =>
        AppendColumnDefinitions(
            builder,
            columns,
            column => (column.Name, column.Type, Comment: (string?)null));

    private static void AppendColumnDefinitions<T>(
        StringBuilder builder,
        IReadOnlyList<T> columns,
        Func<T, (string Name, string Type, string? Comment)> selector)
    {
        for (var i = 0; i < columns.Count; i++)
        {
            var (name, type, comment) = selector(columns[i]);
            var comma = i < columns.Count - 1 ? "," : string.Empty;
            builder.AppendLine(SqlColumnFormatter.FormatColumnLine(name, type, comment, comma));
        }
    }
}
