-- Generated by ClickHouseSchemaGen. Do not edit manually.
-- Must sort before every init script: they record themselves into this table.

CREATE TABLE IF NOT EXISTS schema_migrations
(
    version             String,
    name                String,
    checksum            String,
    applied_at          DateTime,
    kind                LowCardinality(String) DEFAULT 'migration'
)
ENGINE = MergeTree
ORDER BY version;

