-- Generated by ClickHouseSchemaGen. Do not edit manually.

CREATE TABLE orders_queue
(
    order_id             String,
    category             LowCardinality(String),
    `price.currency`     String,  -- nested message
    `price.amount`       Float64,  -- nested message
    quantity             UInt32,
    `event_time.seconds` Int64,  -- nested message
    `event_time.nanos`   Int32,  -- nested message
    status               Enum8('ORDER_STATUS_UNSPECIFIED' = 0, 'ORDER_STATUS_CREATED' = 1, 'ORDER_STATUS_PAID' = 2),  -- proto enum
    tags                 Array(LowCardinality(String)),  -- proto repeated
    items                Nested(sku String, qty UInt32, unit_price Float64, line_status Enum8('ORDER_STATUS_UNSPECIFIED' = 0, 'ORDER_STATUS_CREATED' = 1, 'ORDER_STATUS_PAID' = 2)),  -- proto repeated message
    metadata             Map(String, String),  -- proto map
    note                 Nullable(String),  -- proto optional
    `card.last4`         String,  -- nested message
    `card.network`       String,  -- nested message
    `cash.received`      Float64,  -- nested message
    `wallet.provider`    String,  -- nested message
    `wallet.wallet_id`   String,  -- nested message
    payment              Enum8('absent' = 0, 'card' = 11, 'cash' = 12, 'wallet' = 13),  -- oneof presence
    promo_code           Nullable(String),  -- well-known type
    status_history       Array(Enum8('ORDER_STATUS_UNSPECIFIED' = 0, 'ORDER_STATUS_CREATED' = 1, 'ORDER_STATUS_PAID' = 2)),  -- proto repeated
    loyalty_points       Nullable(Int32),  -- proto optional
    _key                 String,  -- kafka message key
    `_headers.name`      Array(String),  -- kafka message headers
    `_headers.value`     Array(String),  -- kafka message headers
    headers_name         Array(LowCardinality(String)) ALIAS CAST(`_headers.name`, 'Array(LowCardinality(String))'),  -- kafka message headers
    headers_value        Array(String) ALIAS `_headers.value`,  -- kafka message headers
    key_order_id         String ALIAS if(length(_key) <= 6, '', if(reinterpretAsUInt8(substring(substring(_key, 6 + 1), 1, 1)) != bitOr(bitShiftLeft(1, 3), 2), '', if(reinterpretAsUInt8(substring(substring(_key, 6 + 1), 2, 1)) < 128, substring(substring(_key, 6 + 1), 3, reinterpretAsUInt8(substring(substring(_key, 6 + 1), 2, 1))), if(reinterpretAsUInt8(substring(substring(_key, 6 + 1), 3, 1)) >= 128, '', substring(substring(_key, 6 + 1), 4, bitOr(bitAnd(reinterpretAsUInt8(substring(substring(_key, 6 + 1), 2, 1)), 127), bitShiftLeft(reinterpretAsUInt8(substring(substring(_key, 6 + 1), 3, 1)), 7)))))))  -- decoded kafka key field
)
ENGINE = Kafka
SETTINGS
    kafka_broker_list = 'kafka:9092',
    kafka_topic_list = 'orders',
    kafka_group_name = 'clickhouse-orders',
    kafka_format = 'ProtobufSingle',
    kafka_schema = 'order_event:OrderEvent',
    kafka_schema_registry_skip_bytes = 6,
    kafka_num_consumers = 1,
    flatten_nested = 0,
    input_format_protobuf_oneof_presence = 1,
    input_format_protobuf_flatten_google_wrappers = 1;

