-- Generated by ClickHouseSchemaGen. Do not edit manually.

CREATE TABLE orders
(
    order_id             String,
    category             LowCardinality(String),
    currency             LowCardinality(String),
    amount               Float64,
    quantity             UInt32,
    status               LowCardinality(String),
    event_time           DateTime64(3)
)
ENGINE = MergeTree
ORDER BY (event_time, order_id);

CREATE MATERIALIZED VIEW orders_mv TO orders AS
SELECT
    order_id                     AS order_id,
    category                     AS category,
    `price.currency`             AS currency,
    `price.amount`               AS amount,
    quantity                     AS quantity,
    toString(status)             AS status,
    fromUnixTimestamp64Milli(event_time_unix_ms) AS event_time
FROM orders_queue;

CREATE TABLE orders_agg_1m
(
    minute        DateTime,
    category      LowCardinality(String),
    orders_count  UInt64,
    total_amount  Float64,
    total_qty     UInt64
)
ENGINE = SummingMergeTree
ORDER BY (minute, category);

CREATE MATERIALIZED VIEW orders_agg_mv TO orders_agg_1m AS
SELECT
    toStartOfMinute(event_time) AS minute,
    category,
    count()                     AS orders_count,
    sum(amount)                 AS total_amount,
    sum(quantity)               AS total_qty
FROM orders
GROUP BY minute, category;
