-- Generated by ClickHouseSchemaGen. Do not edit manually.

CREATE TABLE shipments_queue
(
    shipment_id          String,
    order_id             String,
    `shipped_at.seconds` Int64,  -- nested message
    `shipped_at.nanos`   Int32,  -- nested message
    status               Enum8('SHIPMENT_STATUS_UNSPECIFIED' = 0, 'SHIPMENT_STATUS_CREATED' = 1, 'SHIPMENT_STATUS_IN_TRANSIT' = 2, 'SHIPMENT_STATUS_DELIVERED' = 3, 'SHIPMENT_STATUS_FAILED' = 4),  -- proto enum
    `destination.country` String,  -- nested message
    `destination.city`   String,  -- nested message
    `destination.street` String,  -- nested message
    `destination.postal_code` String,  -- nested message
    checkpoints          Nested(recorded_at_seconds Int64, recorded_at_nanos Int32, location String, status Enum8('SHIPMENT_STATUS_UNSPECIFIED' = 0, 'SHIPMENT_STATUS_CREATED' = 1, 'SHIPMENT_STATUS_IN_TRANSIT' = 2, 'SHIPMENT_STATUS_DELIVERED' = 3, 'SHIPMENT_STATUS_FAILED' = 4)),  -- proto repeated message
    carrier_metadata     Map(String, String),  -- proto map
    instructions         Nullable(String),  -- proto optional
    `delivered.delivered_at.seconds` Int64,  -- nested message
    `delivered.delivered_at.nanos` Int32,  -- nested message
    `delivered.signed_by` String,  -- nested message
    `failed.reason`      String,  -- nested message
    `failed.retry_count` Nullable(Int32),  -- well-known type
    delivery_outcome     Enum8('absent' = 0, 'delivered' = 9, 'failed' = 10),  -- oneof presence
    priority             Nullable(Int32),  -- well-known type
    status_history       Array(Enum8('SHIPMENT_STATUS_UNSPECIFIED' = 0, 'SHIPMENT_STATUS_CREATED' = 1, 'SHIPMENT_STATUS_IN_TRANSIT' = 2, 'SHIPMENT_STATUS_DELIVERED' = 3, 'SHIPMENT_STATUS_FAILED' = 4))  -- proto repeated
)
ENGINE = Kafka
SETTINGS
    kafka_broker_list = 'kafka:9092',
    kafka_topic_list = 'shipments',
    kafka_group_name = 'clickhouse-shipments',
    kafka_format = 'ProtobufSingle',
    kafka_schema = 'shipment_event:ShipmentEvent',
    kafka_schema_registry_skip_bytes = 6,
    kafka_num_consumers = 1,
    flatten_nested = 0,
    input_format_protobuf_oneof_presence = 1,
    input_format_protobuf_flatten_google_wrappers = 1;

