-- Generated by ClickHouseSchemaGen. Do not edit manually.

-- Protobuf wire-format helpers for decoding the Kafka key (_key) in materialized views.
-- (value, byte length) of the varint at 1-based position p
CREATE OR REPLACE FUNCTION protobufWireVarint AS (m, p) ->
    arrayFold(
        (acc, b) -> if(
            acc.3 = 1,
            acc,
            (bitOr(acc.1, bitShiftLeft(toUInt64(bitAnd(b, 127)), 7 * acc.2)), acc.2 + 1, toUInt8(b < 128))),
        arrayMap(i -> reinterpretAsUInt8(substring(m, p + i, 1)), range(10)),
        (toUInt64(0), toUInt64(0), toUInt8(0)));

CREATE OR REPLACE FUNCTION protobufWireValueSize AS (m, wire_type, value_pos) ->
    toUInt64(multiIf(
        wire_type = 0, protobufWireVarint(m, value_pos).2,
        wire_type = 1, 8,
        wire_type = 2, arrayMap(v -> v.1 + v.2, [protobufWireVarint(m, value_pos)])[1],
        wire_type = 5, 4,
        length(m) + 1));

-- acc: (next position, value position of field_number or 0, its wire type)
CREATE OR REPLACE FUNCTION protobufWireStep AS (m, field_number, acc, tag) ->
    arrayMap(
        x -> (
            x.3 + protobufWireValueSize(m, x.2, x.3),
            if(x.1 = field_number, x.3, acc.2),
            if(x.1 = field_number, x.2, acc.3)),
        [(bitShiftRight(tag.1, 3), bitAnd(tag.1, 7), acc.1 + tag.2)])[1];

CREATE OR REPLACE FUNCTION protobufWireField AS (m, field_number) ->
    arrayMap(
        msg -> arrayFold(
            (acc, i) -> if(
                acc.1 > length(msg),
                acc,
                protobufWireStep(msg, field_number, acc, protobufWireVarint(msg, acc.1))),
            range(length(msg)),
            (toUInt64(1), toUInt64(0), toUInt64(0))),
        [m])[1];

CREATE OR REPLACE FUNCTION protobufWireHas AS (m, field_number) ->
    protobufWireField(m, field_number).2 > 0;

-- Payload of a length-delimited field (string, bytes, nested message); '' when absent.
CREATE OR REPLACE FUNCTION protobufWireBytes AS (m, field_number) ->
    arrayMap(
        msg -> arrayMap(
            f -> if(
                f.2 = 0 OR f.3 != 2,
                '',
                arrayMap(len -> substring(msg, f.2 + len.2, len.1), [protobufWireVarint(msg, f.2)])[1]),
            [protobufWireField(msg, field_number)])[1],
        [m])[1];

-- Raw 64-bit value of a varint, fixed64 or fixed32 field; 0 when absent.
CREATE OR REPLACE FUNCTION protobufWireBits AS (m, field_number) ->
    arrayMap(
        msg -> arrayMap(
            f -> toUInt64(multiIf(
                f.2 = 0, 0,
                f.3 = 0, protobufWireVarint(msg, f.2).1,
                f.3 = 1, reinterpretAsUInt64(substring(msg, f.2, 8)),
                f.3 = 5, toUInt64(reinterpretAsUInt32(substring(msg, f.2, 4))),
                0)),
            [protobufWireField(msg, field_number)])[1],
        [m])[1];

CREATE OR REPLACE FUNCTION protobufWireZigZag AS (bits) ->
    arrayMap(
        v -> if(bitAnd(v, 1) = 0, reinterpretAsInt64(bitShiftRight(v, 1)), -1 - reinterpretAsInt64(bitShiftRight(v, 1))),
        [bits])[1];

-- shipments_queue has a protobuf Kafka key (Sandbox.Contracts.ShipmentKey, Sandbox.Contracts); ClickHouse exposes it only as raw _key String.
-- Materialized views over this table can map the decoded key columns like value columns:
--   `_key.shipment_id` String

CREATE TABLE shipments_queue
(
    shipment_id          String,
    order_id             String,
    `shipped_at.seconds` Int64,  -- nested message
    `shipped_at.nanos`   Int32,  -- nested message
    status               Enum8('SHIPMENT_STATUS_UNSPECIFIED' = 0, 'SHIPMENT_STATUS_CREATED' = 1, 'SHIPMENT_STATUS_IN_TRANSIT' = 2, 'SHIPMENT_STATUS_DELIVERED' = 3, 'SHIPMENT_STATUS_FAILED' = 4),  -- proto enum
    `destination.country` LowCardinality(String),  -- nested message
    `destination.city`   LowCardinality(String),  -- nested message
    `destination.street` String,  -- nested message
    `destination.postal_code` String,  -- nested message
    checkpoints          Nested(recorded_at_seconds Int64, recorded_at_nanos Int32, location String, status Enum8('SHIPMENT_STATUS_UNSPECIFIED' = 0, 'SHIPMENT_STATUS_CREATED' = 1, 'SHIPMENT_STATUS_IN_TRANSIT' = 2, 'SHIPMENT_STATUS_DELIVERED' = 3, 'SHIPMENT_STATUS_FAILED' = 4), scans Array(Tuple(code String, operator_note Nullable(String)))),  -- proto repeated message
    carrier_metadata     Map(String, String),  -- proto map
    instructions         Nullable(String),  -- proto optional
    `delivered.delivered_at.seconds` Int64,  -- nested message
    `delivered.delivered_at.nanos` Int32,  -- nested message
    `delivered.signed_by` String,  -- nested message
    `failed.reason`      String,  -- nested message
    `failed.retry_count` Nullable(Int32),  -- well-known type
    delivery_outcome     Enum8('absent' = 0, 'delivered' = 9, 'failed' = 10),  -- oneof presence
    priority             Nullable(Int32),  -- well-known type
    status_history       Array(Enum8('SHIPMENT_STATUS_UNSPECIFIED' = 0, 'SHIPMENT_STATUS_CREATED' = 1, 'SHIPMENT_STATUS_IN_TRANSIT' = 2, 'SHIPMENT_STATUS_DELIVERED' = 3, 'SHIPMENT_STATUS_FAILED' = 4)),  -- proto repeated
    documents            Tuple(labels Array(Tuple(id String, pages Nullable(Int32))), customs_forms Array(Tuple(id String, pages Nullable(Int32))))  -- nested message
)
ENGINE = Kafka
SETTINGS
    kafka_broker_list = 'kafka:9092',
    kafka_topic_list = 'shipments',
    kafka_group_name = 'clickhouse-shipments',
    kafka_format = 'ProtobufSingle',
    kafka_schema = 'shipment_event:ShipmentEvent',
    kafka_schema_registry_skip_bytes = 6,
    kafka_num_consumers = 1,
    flatten_nested = 0,
    input_format_protobuf_oneof_presence = 1,
    input_format_protobuf_flatten_google_wrappers = 1;

