-- Generated by ClickHouseSchemaGen. Do not edit manually.

CREATE TABLE orders
(
    order_id             String,
    category             LowCardinality(String),
    currency             LowCardinality(String),
    amount               Float64,
    quantity             UInt32,
    status               LowCardinality(String),
    payment              LowCardinality(String),
    event_time           DateTime64(3)
)
ENGINE = MergeTree
ORDER BY (event_time, order_id);

CREATE TABLE shipments
(
    shipment_id          String,
    order_id             String,
    status               LowCardinality(String),
    country              LowCardinality(String),
    city                 LowCardinality(String),
    delivery_outcome     LowCardinality(String),
    shipped_at           DateTime64(3)
)
ENGINE = MergeTree
ORDER BY (shipped_at, shipment_id);

CREATE MATERIALIZED VIEW orders_mv TO orders AS
SELECT
    order_id                     AS order_id,
    category                     AS category,
    `price.currency`             AS currency,
    `price.amount`               AS amount,
    quantity                     AS quantity,
    toString(status)             AS status,
    toString(payment)            AS payment,
    toDateTime64(event_time.seconds + event_time.nanos / 1000000000.0, 3) AS event_time
FROM orders_queue;

CREATE MATERIALIZED VIEW shipments_mv TO shipments AS
SELECT
    shipment_id                  AS shipment_id,
    order_id                     AS order_id,
    toString(status)             AS status,
    `destination.country`        AS country,
    `destination.city`           AS city,
    toString(delivery_outcome)   AS delivery_outcome,
    toDateTime64(shipped_at.seconds + shipped_at.nanos / 1000000000.0, 3) AS shipped_at
FROM shipments_queue;

CREATE TABLE orders_agg_1m
(
    minute        DateTime,
    category      LowCardinality(String),
    orders_count  UInt64,
    total_amount  Float64,
    total_qty     UInt64
)
ENGINE = SummingMergeTree
ORDER BY (minute, category);

CREATE MATERIALIZED VIEW orders_agg_mv TO orders_agg_1m AS
SELECT
    toStartOfMinute(event_time) AS minute,
    category,
    count()                     AS orders_count,
    sum(amount)                 AS total_amount,
    sum(quantity)               AS total_qty
FROM orders
GROUP BY minute, category;

CREATE TABLE shipments_agg_1m
(
    minute           DateTime,
    status           LowCardinality(String),
    shipments_count  UInt64
)
ENGINE = SummingMergeTree
ORDER BY (minute, status);

CREATE MATERIALIZED VIEW shipments_agg_mv TO shipments_agg_1m AS
SELECT
    toStartOfMinute(shipped_at) AS minute,
    status,
    count()                     AS shipments_count
FROM shipments
GROUP BY minute, status;
