-- Generated by ClickHouseSchemaGen. Do not edit manually.

CREATE TABLE IF NOT EXISTS schema_migrations
(
    version             String,
    name                String,
    checksum            String,
    applied_at          DateTime
)
ENGINE = MergeTree
ORDER BY version;

