<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <UserSecretsId>dotnet-Sandbox.App-1dc92241-e459-4423-8bea-880693ca227c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClickHouse.Client" />
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Confluent.SchemaRegistry" />
    <PackageReference Include="Confluent.SchemaRegistry.Serdes.Protobuf" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sandbox.Contracts\Sandbox.Contracts.csproj" />
  </ItemGroup>
</Project>
