<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ClickHouseSchemaGen.Migrator</RootNamespace>
    <SkipClickHouseCodegen>true</SkipClickHouseCodegen>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClickHouse.Client" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <ProjectReference Include="..\ClickHouseSchemaGen\ClickHouseSchemaGen.csproj" />
  </ItemGroup>

</Project>
