using System.Text;
using ClickHouseSchemaGen.Models;

namespace ClickHouseSchemaGen;

public sealed class KafkaTableGenerator
{
    public string Generate(KafkaTableConfig config, IReadOnlyList<ClickHouseColumn> columns)
    {
        var builder = new StringBuilder();
        builder.AppendLine("-- Generated by ClickHouseSchemaGen. Do not edit manually.");
        builder.AppendLine();
        builder.AppendLine($"CREATE TABLE {config.TableName}");
        builder.AppendLine("(");

        for (var i = 0; i < columns.Count; i++)
        {
            var column = columns[i];
            var comma = i < columns.Count - 1 ? "," : string.Empty;
            var name = column.Name.Contains('.') ? $"`{column.Name}`" : column.Name;
            var comment = string.IsNullOrWhiteSpace(column.Comment) ? string.Empty : $"  -- {column.Comment}";

            builder.AppendLine($"    {name,-20} {column.Type}{comma}{comment}");
        }

        builder.AppendLine(")");
        builder.AppendLine("ENGINE = Kafka");
        builder.AppendLine("SETTINGS");
        builder.AppendLine($"    kafka_broker_list = '{config.Kafka.BrokerList}',");
        builder.AppendLine($"    kafka_topic_list = '{config.Kafka.Topic}',");
        builder.AppendLine($"    kafka_group_name = '{config.Kafka.GroupName}',");
        builder.AppendLine("    kafka_format = 'ProtobufSingle',");
        builder.AppendLine($"    kafka_schema = '{config.ProtoFile}:{config.MessageName}',");
        builder.AppendLine($"    kafka_schema_registry_skip_bytes = {config.Kafka.SkipBytes},");
        builder.AppendLine($"    kafka_num_consumers = {config.Kafka.NumConsumers};");

        return builder.ToString();
    }
}
